/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_go_core_Detector */

#ifndef _Included_com_go_core_Detector
#define _Included_com_go_core_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_go_core_Detector
 * Method:    Detect
 * Signature: (Ljava/lang/Object;III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_go_core_Detector_Detect
  (JNIEnv *, jclass, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
